<html>
    <head></head>
    <body>
        <script>
            async function mul(a,b){
                var ans = await a*b;
                return ans
            }
            mul(12,3).then(function(res){console.log(res)}).catch(function(err){console.log(err)})


            function div(a,b){
                if(b===0){
                    return Promise.reject('denominator cannot be zero')
                }
                else{
                    return Promise.resolve(a/b)
                }
            }

            div(12,4)
            .then(function(res){
                console.log(res)
            })
            .catch(function(err){
                console.log(err)
            })

            div(12,0)
            .then(function(res){
                console.log(res)
            })
            .catch(function(err){
                console.log(err)
            })

            var x = div(33,0);
            console.log(x)
        </script>
    </body>
</html>
<!-- 
    promise states
        fullfilled
        rejected
        pending
 -->